--- #YAML:1.0
name:                POE-Component-SNMP-Session
version:             0.11
abstract:            Wrap Net-SNMP's SNMP::Session in POE
license:             perl
author:              
    - Rob Bloodgood <rdb@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    POE:                           0.38
    SNMP:                          3.1
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
