--- #YAML:1.0
name:               POE-Component-SNMP-Session
version:            0.1200
abstract:           Wrap Net-SNMP's SNMP::Session in POE
author:
    - Rob Bloodgood <rdb@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:         0.38
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
